name: Run tests and push build to Okteto

on:
  pull_request:
     types:
     - closed
     branches:
      - release-*
      
jobs:
  deployment-testing:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Installing Okteto CLI
        run: |
          curl https://get.okteto.com -sSfL | sh
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Ejecutar Pruebas Unitarias
        run: mvn test -Dtest=BookServiceTest
      - name: Ejecutar Pruebas de Integración
        run: mvn test -Dtest=OpenLibraryServiceTest
      - name: Ejecutar Pruebas de API Rest
        run: mvn test -Dtest=APIRestTest
      #- name: Ejecutar Pruebas de Selenium
        #run: mvn test -Dtest=WebInterfaceTest
      - name: Building Docker Image
        run: |
          mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
      - name: Logging into Docker Hub
        run: |
          docker login --username="${{ secrets.DOCKERHUB_USERNAME }}" --password="${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Pushing Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout) | tee dockerPush.txt
      - name: Generating the DockerPush artifact
        uses: actions/upload-artifact@v3
        with:
          name: DockerPush 
          path: dockerPush.txt
      - name: Closing Docker Hub
        run: |
          docker logout
      - name: Logging into Okteto
        run: |
          okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
      - name: Deploying to Okteto
        run: |
          okteto deploy --wait --build
