name: Run all tests

on:
  pull_request:
    types: [closed]
    branches:
      - trunk
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código Fuente
        uses: actions/checkout@v3
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      
      - name: Ejecutar Pruebas Unitarias
        run: mvn test -Dtest=BookServiceUnitTests
      - name: Ejecutar Pruebas de Integración
        run: mvn test -Dtest=OpenLibraryServiceIntegrationTests
      - name: Ejecutar Pruebas de API Rest
        run: mvn test -Dtest=RestAssuredE2ETests
      - name: Ejecutar Pruebas de Selenium
        run: mvn test -Dtest=SeleniumE2ETests
    
